// Do not edit this file

const ct = require("../src/codingTest");

describe("Coding Test", () => {
  test("shows the day number with the smallest temperature spread", () => {
    expect(ct.dayMinTempSpread("./data/weather.dat")).toBe("14");
  });

  test("shows the name of the team with the smallest point differenc", () => {
    expect(ct.teamMinPointSpread("./data/weather.dat")).toBe("Aston_Villa");
  });
});
