// Do not edit this file

const ct = require("../src/codingTest");

describe("Coding Test", () => {
  test("shows the day number with the smallest temperature spread", async () => {
    expect(await ct.dayMinTempSpread("weather.dat")).toBe("14");
  });

  test("shows the name of the team with the smallest point differenc", async () => {
    expect(await ct.teamMinPointSpread("football.dat")).toBe("Aston_Villa");
  });
});
