// Do not edit this file. Use this function to "mimic" asynchronous requests for data.

const fs = require("fs");
const fsPromises = fs.promises;

async function getDataFromFile(fileName) {
  const data = await fsPromises.readFile(
    __dirname + `/../test/data/${fileName}`
  );
  return data.toString();
}

module.exports = getDataFromFile;
